// ⚠️ scripts/collect-dart.js가 자동 생성하는 파일 — 직접 수정하지 말 것
// 현재 내용: 수집 실행 전 임시 시드 (기존 46개사, avg_salary_man null → dart-salary.js가 DART 실시간 폴백)
// 수집 실행 후 시총 상위 500개 + 사전 수집 연봉으로 전체 덮어써짐.
// 별칭 추가/수정: scripts/aliases.json 수정 후 스크립트 재실행.
export const DART_DATA = [
 { "name": "삼성전자", "corp_code": "00126380", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["삼성전자(주)"] },
 { "name": "SK하이닉스", "corp_code": "00164779", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["sk하이닉스(주)"] },
 { "name": "현대자동차", "corp_code": "00164742", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["현대차"] },
 { "name": "기아", "corp_code": "00106641", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["기아자동차"] },
 { "name": "LG전자", "corp_code": "00401731", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "카카오", "corp_code": "00258801", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["(주)카카오"] },
 { "name": "NAVER", "corp_code": "00266961", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["네이버"] },
 { "name": "LG화학", "corp_code": "00356361", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "삼성SDI", "corp_code": "00126362", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "삼성바이오로직스", "corp_code": "00877059", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "셀트리온", "corp_code": "00413046", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "POSCO홀딩스", "corp_code": "00155319", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["포스코홀딩스", "포스코"] },
 { "name": "현대모비스", "corp_code": "00164788", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "KT", "corp_code": "00190321", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["케이티"] },
 { "name": "SK텔레콤", "corp_code": "00159023", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "LG유플러스", "corp_code": "00231363", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "삼성생명", "corp_code": "00126256", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "한국전력공사", "corp_code": "00159193", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["한국전력", "한전"] },
 { "name": "크래프톤", "corp_code": "00760971", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "엔씨소프트", "corp_code": "00261443", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "하이브", "corp_code": "01204056", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "한화에어로스페이스", "corp_code": "00126566", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "한화비전", "corp_code": "01867758", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "한화오션", "corp_code": "00111704", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "CJ제일제당", "corp_code": "00635134", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "한미약품", "corp_code": "00828497", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "KB금융", "corp_code": "00688996", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["kb금융지주"] },
 { "name": "신한지주", "corp_code": "00382199", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["신한금융지주"] },
 { "name": "하나금융지주", "corp_code": "00547583", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "우리금융지주", "corp_code": "01350869", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "기업은행", "corp_code": "00149646", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["ibk기업은행"] },
 { "name": "현대건설", "corp_code": "00164478", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "GS건설", "corp_code": "00120030", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "롯데쇼핑", "corp_code": "00120526", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "신세계", "corp_code": "00136378", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "현대백화점", "corp_code": "00428251", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "카카오뱅크", "corp_code": "01133217", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "SK이노베이션", "corp_code": "00631518", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "두산에너빌리티", "corp_code": "00159616", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] },
 { "name": "LG에너지솔루션", "corp_code": "01515323", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": ["lg엔솔"] },
 { "name": "삼성물산", "corp_code": "00149655", "stock_code": null, "market_cap_rank": null, "avg_salary_man": null, "employee_count": null, "bsns_year": null, "aliases": [] }
];
